.Dd 2025-07-15
.Dt PROMETHEUS 1
.Os francescosaccone.com
.Sh NAME
.Nm prometheus
.Nd Simple package manager.
.Sh SYNOPSIS
.Nm
.Fl i
.Op Fl p Ar prefix
.Ar package ...
.Nm
.Fl u
.Op Fl p Ar prefix
.Op Fl r
.Ar package ...
.Nm
.Fl l
.Op Fl p Ar prefix
.Nm
.Fl a
.Sh DESCRIPTION
.Nm
is a package manager for POSIX systems. It works by pairing it to a package
repository as described in the README file of its source tree.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl i
Install
.Ar package .
.It Fl u
Uninstall
.Ar package .
.It Fl l
List installed packages.
.It Fl a
List all packages.
.It Fl r
Uninstall
.Ar package
and all its dependencies. Requires
.Fl u .
.It Fl p Ar prefix
Use
.Ar prefix
as the prefix directory for installing packages. The default is defined at
compile time.
.Sh CUSTOMIZATION
.Nm
can be customized by editing config.def.h and (re)compiling the source code.
.Sh AUTHORS
.An Francesco Saccone Aq Mt francesco@francescosaccone.com
