.Dd 2025-07-03
.Dt PROMETHEUS 1
.Os francescosaccone.com
.Sh NAME
.Nm prometheus
.Nd Simple package manager.
.Sh SYNOPSIS
.Nm
.Fl a
.Op Fl s Ar repo
.Nm
.Fl i
.Op Fl s Ar repo
.Op Fl p Ar prefix
.Ar package ...
.Nm
.Fl l
.Op Fl s Ar repo
.Op Fl p Ar prefix
.Nm
.Fl u
.Op Fl s Ar repo
.Op Fl p Ar prefix
.Op Fl r
.Ar package ...
.Sh DESCRIPTION
.Nm
is a package manager for POSIX systems. It works by pairing it to a package
repository as described in the README file of its source tree.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl a
List all packages.
.It Fl i
Install
.Ar package .
.It Fl l
List installed packages.
.It Fl p Ar prefix
Use
.Ar prefix
as the prefix directory for installing packages. The default is "/".
.It Fl r
Uninstall
.Ar package
and all its dependencies. Requires
.Fl u .
.It Fl s
Use
.Ar repo
as the package repository. The default is "/src".
.It Fl u
Uninstall
.Ar package .
.Sh CUSTOMIZATION
.Nm
can be customized by editing config.def.h and (re)compiling the source code.
.Sh AUTHORS
.An Francesco Saccone Aq Mt francesco@francescosaccone.com
